repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@3.6.2 # npm
  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 41.168.5
    hooks:
      - id: renovate-config-validator
        files: .*\.json5$
